apiVersion: v1
kind: Service
metadata:
  name: fullstack-backend
  labels:
    app: fullstack-demo
spec:
  selector:
    app: fullstack-demo
    component: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
