apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-backend
  labels:
    app: fullstack-demo
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-demo
      component: backend
  template:
    metadata:
      labels:
        app: fullstack-demo
        component: backend
    spec:
      containers:
      - name: backend
        image: alnahhaas/fullstack_demo_backend:latest
        ports:
        - containerPort: 5000
