apiVersion: v1
kind: Service
metadata:
  name: fullstack-frontend
  labels:
    app: fullstack-demo
spec:
  selector:
    app: fullstack-demo
    component: frontend
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
