apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-frontend
  labels:
    app: fullstack-demo
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-demo
      component: frontend
  template:
    metadata:
      labels:
        app: fullstack-demo
        component: frontend
    spec:
      containers:
      - name: frontend
        image: alnahhaas/fullstack_demo_frontend:latest
        ports:
        - containerPort: 80
